version: "3"
services:
  rabbitmq:
    build: rabbitmq-delayed
    ports:
      - 5672:5672
      - 15672:15672
  schedule:
    build: ./schedule
    ports:
      - 8000:8000
    environment:
      - LOG_LEVEL=warn
      - RABBITMQ__HOST=amqp://rabbitmq
      - POSTGRES__HOST=postgres://postgres:5432
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=pgdb
    ports:
      - 5432:5432
  dispatch:
    build: ./dispatch
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - LOG_LEVEL=warn
      - RABBITMQ__HOST=amqp://rabbitmq
  logs:
    build: ./logs
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - LOG_LEVEL=warn
      - RABBITMQ__HOST=amqp://rabbitmq
      - ELASTICSEARCH__HOST=http://elasticsearch:9200
  elasticsearch:
    image: elasticsearch:5.3
    ports:
      - 9200:9200
  kibana:
    image: kibana:5.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200